general:
  visdom: False
  kg_expansion_reward: 0.1
  use_negative_reward: False
  random_seed: 42
  use_cuda: True  # disable this when running on machine without cuda
  setting: "ours_note"  # "noquery", "query", "ours_note"
  node_capacity: 64

training:
  batch_size: 20
  parallel: True  # Whether to run all environments asynchronously or one after the other.
  max_nb_steps_per_episode: 20  # after this many steps, a game is terminated
  max_episode: 500000
  learn_start_from_this_episode: 100
  target_net_update_frequency: 1000  # sync target net with online net per this many epochs
  discount_gamma: 0.90
  verb_entropy_coefficient: 0.00  # encourage the agent to generate diverse verbs
  optimizer:
    step_rule: 'adam'  # adam
    learning_rate: 0.00025
    clip_grad_norm: 5
    learning_rate_warmup_until: 1000

evaluate:
  run_eval: False
  batch_size: 20

checkpoint:
  report_frequency: 1000  # episode
  experiment_tag: 'test'
  load_pretrained: False  # during test, enable this so that the agent load your pretrained model
  load_from_tag: 'pretrained_model'

replay:
  replay_memory_capacity: 100000  # adjust this depending on your RAM size
  replay_memory_priority_fraction: 0.5
  accumulate_reward_from_final: True
  update_per_k_game_steps: 2
  replay_batch_size: 64
  multi_step: 3
  replay_sample_history_length: 4
  replay_sample_update_from: 2

epsilon_greedy:
  noisy_net: True  # if this is true, then epsilon greedy is disabled
  epsilon_anneal_episodes: 100000  # -1 if not annealing
  epsilon_anneal_from: 1.0
  epsilon_anneal_to: 0.1

model:
  word_embedding_trainable: True
  embedding_dropout: 0.1
  encoder_layers: 1
  encoder_conv_num: 4
  block_hidden_dim: 128
  n_heads: 4
  attention_dropout: 0.1
  block_dropout: 0.1
  recurrent: False

tw:
  name: "TextWorld-CookingAFK_Easy-v0"
  seed: 20220110  # Random seed to control game generation.
  # max_steps: 30  # Maximum steps in an episode.
  oracle_name: "Charlie"  # Name of the oracle to ask for information, i.e., "Ask [Oracle] how to ..."
  recipe: 1  # Number of ingredients in the recipe.
  take: 1  # Number of ingredients to find.
  open: True  # Whether containers/doors need to be opened.
  cook: False # Whether some ingredients need to be cooked.
  cut: False  # Whether some ingredients need to be cut.
  knife_in_inventory: False
  recipe_seed: 0  # Random seed used for generating the recipe.
  nb_furniture_distractors: 0  # Number of additional distractor furnitures to add.
  nb_food_distractors: 0  # Number of additional distractor ingredients to add.
  split: null  # Default: game is drawn from the joint distribution over train, valid, and test.
  verbose: False

git:
  last_commit: ""
  git_diff: ""